// AS Grocery Backend Catalog Data

export const GROCERY_CATEGORIES = [
  { id: 'fruits-veg', name: 'Fruits & Vegetables', icon: '🥦', description: 'Fresh, organic fruits & farm-fresh vegetables' },
  { id: 'dairy-bakery', name: 'Dairy, Eggs & Bakery', icon: '🥛', description: 'Fresh milk, butter, cheeses, eggs & artisan breads' },
  { id: 'staples', name: 'Staples, Rice & Oils', icon: '🌾', description: 'Premium rice, pulses, cooking oils, flours & spices' },
  { id: 'beverages', name: 'Beverages & Juices', icon: '🧃', description: 'Cold-pressed juices, sodas, teas & coffee' },
  { id: 'snacks', name: 'Snacks & Packaged Foods', icon: '🍿', description: 'Chips, chocolates, nuts & quick munchies' },
  { id: 'meat-seafood', name: 'Meat & Poultry', icon: '🥩', description: 'Fresh cuts, chicken, seafood & eggs' },
  { id: 'organic', name: 'Daily Needs', icon: '🌿', description: '100% certified organic groceries & cold pressed oils' },
];

export const ALL_GROCERIES = [
  {
    name: 'Fresh Organic Bananas',
    price: 40.00,
    originalPrice: 50.00,
    category: 'Fruits & Vegetables',
    subCategory: 'Fresh Fruits',
    stock: 45,
    unit: '1 kg',
    rating: 4.9,
    reviewCount: 154,
    description: 'Naturally ripened, sweet, and nutritious organic Robusta bananas directly from certified local orchards.',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    tags: ['Farm Fresh', 'Fruits', 'Organic']
  },
  {
    name: 'Farm Fresh Red Tomatoes',
    price: 34.00,
    originalPrice: 40.00,
    category: 'Fruits & Vegetables',
    subCategory: 'Fresh Vegetables',
    stock: 60,
    unit: '1 kg',
    rating: 4.8,
    reviewCount: 120,
    description: 'Plump, ripe, and juicy country tomatoes freshly harvested from hydroponic greenhouses.',
    imageUrl: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&w=600&q=80',
    tags: ['Best Seller', 'Vegetables', 'Hydroponic']
  },
  {
    name: 'Golden Mountain Potatoes',
    price: 22.00,
    originalPrice: 25.00,
    category: 'Fruits & Vegetables',
    subCategory: 'Fresh Vegetables',
    stock: 80,
    unit: '1 kg',
    rating: 4.7,
    reviewCount: 95,
    description: 'Clean, thin-skinned mountain potatoes perfect for boiling, roasting, and everyday curries.',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    tags: ['Daily Essential', 'Vegetables']
  },
  {
    name: 'Fresh Tender Baby Spinach (Palak)',
    price: 15.00,
    originalPrice: 20.00,
    category: 'Fruits & Vegetables',
    subCategory: 'Leafy Greens',
    stock: 35,
    unit: '1 Bunch (250g)',
    rating: 4.9,
    reviewCount: 88,
    description: 'Crisp, nutrient-dense green spinach leaves freshly cut and hydro-washed for instant cooking.',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80',
    tags: ['Superfood', 'Greens']
  },
  {
    name: 'Organic Red Crisp Apples',
    price: 120.00,
    originalPrice: 146.00,
    category: 'Fruits & Vegetables',
    subCategory: 'Fresh Fruits',
    stock: 25,
    unit: '1 kg (4-5 pcs)',
    rating: 4.9,
    reviewCount: 142,
    description: 'Juicy, sweet, hand-picked Royal Gala apples imported fresh from Washington orchards.',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?auto=format&fit=crop&w=600&q=80',
    tags: ['Best Seller', 'Fruits']
  },
  {
    name: 'Sweet Hydroponic Strawberries',
    price: 99.00,
    originalPrice: 130.00,
    category: 'Fruits & Vegetables',
    subCategory: 'Fresh Fruits',
    stock: 20,
    unit: '200g Pack',
    rating: 4.8,
    reviewCount: 76,
    description: 'Sweet, fragrant, and vibrant red strawberries grown pesticide-free in climate-controlled farms.',
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
    tags: ['Premium', 'Berries']
  },
  {
    name: 'Fresh Red Onions (Pyaz)',
    price: 28.00,
    originalPrice: 35.00,
    category: 'Fruits & Vegetables',
    subCategory: 'Fresh Vegetables',
    stock: 90,
    unit: '1 kg',
    rating: 4.7,
    reviewCount: 110,
    description: 'Pungent, high-flavor Maharashtra red onions perfect for gravies, salads, and everyday cooking.',
    imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
    tags: ['Daily Essential', 'Vegetables']
  },
  {
    name: 'Farm Fresh Whole Milk',
    price: 32.00,
    originalPrice: 38.00,
    category: 'Dairy, Eggs & Bakery',
    subCategory: 'Milk & Dairy',
    stock: 50,
    unit: '1 L',
    rating: 4.8,
    reviewCount: 198,
    description: 'Pasteurized 100% pure cow milk rich in calcium and natural vitamin D.',
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80',
    tags: ['Daily Essential', 'Dairy']
  },
  {
    name: 'Farm Fresh White Eggs',
    price: 42.00,
    originalPrice: 48.00,
    category: 'Dairy, Eggs & Bakery',
    subCategory: 'Eggs',
    stock: 75,
    unit: '6 pcs',
    rating: 4.8,
    reviewCount: 215,
    description: 'High-protein, farm-fresh white eggs carefully inspected and packed for safety.',
    imageUrl: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&w=600&q=80',
    tags: ['Protein Choice', 'Eggs']
  },
  {
    name: 'Artisan Whole Wheat Sourdough Bread',
    price: 65.00,
    originalPrice: 80.00,
    category: 'Dairy, Eggs & Bakery',
    subCategory: 'Bakery & Bread',
    stock: 25,
    unit: '400g Loaf',
    rating: 4.9,
    reviewCount: 84,
    description: 'Freshly baked every morning with 100% whole wheat flour, natural sourdough starter, and zero chemical preservatives.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    tags: ['Fresh Baked', 'Bread']
  },
  {
    name: 'Fresh Malai Paneer Block',
    price: 85.00,
    originalPrice: 105.00,
    category: 'Dairy, Eggs & Bakery',
    subCategory: 'Milk & Dairy',
    stock: 30,
    unit: '200g Pack',
    rating: 4.9,
    reviewCount: 160,
    description: 'Melt-in-the-mouth soft and rich cottage cheese made from 100% pure cow milk.',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
    tags: ['Top Quality', 'Paneer']
  },
  {
    name: 'Premium Royal Basmati Rice',
    price: 340.00,
    originalPrice: 410.00,
    category: 'Staples, Rice & Oils',
    subCategory: 'Rice & Grains',
    stock: 40,
    unit: '5 kg',
    rating: 4.9,
    reviewCount: 130,
    description: 'Aged long-grain aromatic Basmati rice with slender grains that double in length after cooking.',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    tags: ['Aged 2 Years', 'Rice']
  },
  {
    name: 'Extra Virgin Cold Pressed Olive Oil',
    price: 699.00,
    originalPrice: 850.00,
    category: 'Staples, Rice & Oils',
    subCategory: 'Cooking Oils',
    stock: 15,
    unit: '1 L',
    rating: 4.9,
    reviewCount: 42,
    description: 'First cold-pressed Mediterranean olive oil rich in antioxidants and healthy monounsaturated fats.',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    tags: ['Super Saver', 'Oil']
  },
  {
    name: '100% Sharbati Whole Wheat Atta',
    price: 245.00,
    originalPrice: 290.00,
    category: 'Staples, Rice & Oils',
    subCategory: 'Flours & Grains',
    stock: 50,
    unit: '5 kg',
    rating: 4.8,
    reviewCount: 175,
    description: 'Chakki-ground pure whole wheat flour from MP Sehore golden grains for extra soft rotis.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    tags: ['Family Pack', 'Atta']
  },
  {
    name: 'Cold-Pressed Valencia Orange Juice',
    price: 120.00,
    originalPrice: 150.00,
    category: 'Beverages & Juices',
    subCategory: 'Fresh Juices',
    stock: 20,
    unit: '500 ml',
    rating: 4.8,
    reviewCount: 64,
    description: '100% squeezed oranges with pulpy goodness. No added sugar or artificial preservatives.',
    imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=600&q=80',
    tags: ['100% Pure', 'Juices']
  },
  {
    name: 'Pure Organic Himalayan Green Tea',
    price: 195.00,
    originalPrice: 240.00,
    category: 'Beverages & Juices',
    subCategory: 'Tea & Coffee',
    stock: 30,
    unit: '25 Tea Bags',
    rating: 4.9,
    reviewCount: 115,
    description: 'Single-estate antioxidant-rich whole leaf green tea with subtle citrus notes.',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    tags: ['Healthy Living', 'Tea']
  },
  {
    name: 'Premium California Whole Almonds (Badam)',
    price: 399.00,
    originalPrice: 480.00,
    category: 'Snacks & Packaged Foods',
    subCategory: 'Dry Fruits & Nuts',
    stock: 30,
    unit: '500g Pack',
    rating: 4.9,
    reviewCount: 156,
    description: 'Crunchy, jumbo California almonds rich in Vitamin E, dietary fiber, and healthy proteins.',
    imageUrl: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=600&q=80',
    tags: ['Superfood', 'Nuts']
  },
  {
    name: 'Fresh Tender Chicken Breast (Boneless)',
    price: 180.00,
    originalPrice: 220.00,
    category: 'Meat & Poultry',
    subCategory: 'Fresh Poultry',
    stock: 20,
    unit: '500g',
    rating: 4.8,
    reviewCount: 105,
    description: 'Hormone-free, tender boneless chicken breast fillets hygienically cut and vacuum sealed.',
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=600&q=80',
    tags: ['High Protein', 'Poultry']
  },
  {
    name: 'Pure Wild Forest Raw Honey',
    price: 299.00,
    originalPrice: 375.00,
    category: 'Daily Needs',
    subCategory: 'Organic Essentials',
    stock: 20,
    unit: '500g Jar',
    rating: 4.9,
    reviewCount: 88,
    description: 'Unfiltered, unpasteurized 100% pure wild flower honey packed with natural pollen and enzymes.',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    tags: ['100% Organic', 'Honey']
  }
];

export const ALL_BOOKS = ALL_GROCERIES;
export const FEATURED_BOOKS = ALL_GROCERIES;
